import { Box } from "@/components/ui/box";
import { Button, ButtonIcon, ButtonText } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Heading } from "@/components/ui/heading";
import { AddIcon } from "@/components/ui/icon";
import { Text } from "@/components/ui/text";
import { VStack } from "@/components/ui/vstack";
import { useNewTemplateFormValues } from "./NewTemplateFormContext";

// TODO replace any with exercise type generated by supabase
export default function ExerciseForm({
  name,
  id,
}: {
  name: string;
  id: string;
}) {
  const { exercises, addSet } = useNewTemplateFormValues();

  return (
    <Card variant="outline">
      <VStack space="xl">
        <Heading>{name}</Heading>
        <VStack space="sm">
          <Box className="flex flex-row justify-between">
            <VStack space="md">
              <Heading size="sm">Set</Heading>
            </VStack>
            <VStack space="md">
              <Heading size="sm"> lbs</Heading>
            </VStack>
            <VStack space="md">
              <Heading size="sm">Reps</Heading>
            </VStack>
          </Box>
          {exercises &&
            exercises
              .find((exercise) => exercise.info.id == id)
              ?.sets.map((set, i) => (
                // TODO implement editing weight, reps, removing sets
                <Box key={i} className="flex flex-row justify-between">
                  <Text>{i + 1}</Text>
                  <Text>{set.weight}</Text>
                  <Text>{set.reps}</Text>
                </Box>
              ))}
        </VStack>
        <Button
          variant="solid"
          action="secondary"
          size="xs"
          onPress={() => addSet(id)}
        >
          <ButtonText>Add Set</ButtonText>
          <ButtonIcon as={AddIcon} />
        </Button>
      </VStack>
    </Card>
  );
}
